### ISSUE TITLE
AttributeError: 'ModelManager' object has no attribute 'model'

### ISSUE THREAD

**Issue by palashkulsh** [g1ibby/llm-deploy#3]
hey first of all, great project, im trying to deploy mixtral to vast.ai with the following command  but its giving the error.
can you please help in identifying what i maybe doing wrong.

`poetry run llm-deploy model deploy mixtral 10555749`

deploying model mixtral to machine 10555749...
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 135, in main
    app()

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 112, in model_deploy
    appl.model.model(model_name, machine_id)
    ^^^^^^^^^^^^^^^^

AttributeError: 'ModelManager' object has no attribute 'model'

**Comment by g1ibby** [comment]
Hi there,

First of all, thank you for your kind words and for bringing this issue to our attention!

It seems like the error is due to the model name being insufficiently specified. Could you please try using the full version name of the model? You can find this on the model's tag page at Ollama. Here’s how you should modify your command:

`poetry run llm-deploy model deploy mixtral:8x7b-instruct-v0.1-q4_0 10564912`

You can get the full model name from the following page: [Mixtral Tags](https://ollama.com/library/mixtral/tags).

This should resolve the problem for now. I am planning to update the code in the future to accommodate simpler model names, making it more straightforward.

**Comment by palashkulsh** [comment]
again getting similar error. seems like there might be some issue with my installation.
poetry run llm-deploy model deploy mixtral:8x7b-instruct-v0.1-q4_0 10564912
Deploying model mixtral:8x7b-instruct-v0.1-q4_0 to machine 10564912...
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 135, in main
    app()

  File "/home/palash/Documents/programs/mygit/other-repos/llm-deploy/llm_deploy/cli.py", line 112, in model_deploy
    appl.model.model(model_name, machine_id)
    ^^^^^^^^^^^^^^^^

AttributeError: 'ModelManager' object has no attribute 'model'

![image](https://github.com/g1ibby/llm-deploy/assets/5735087/4293b7b6-5b7e-472f-8c1c-ab8b479c7672)

**Comment by g1ibby** [comment]
@palashkulsh Forgot to mention, need to pull new version of the repo

**Comment by palashkulsh** [comment]
Uh-mazing work @g1ibby . your thoughts & work in this repo are amazing. thank you so much for such an impressive and super helpful project.
closing the issue as its started working now.
